# Generated by Django 6.0.5 on 2026-05-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_substance_problempart'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='problempart',
            name='unique_problem_part_label',
        ),
        migrations.RemoveField(
            model_name='stoichiometryproblem',
            name='product_mass',
        ),
        migrations.RemoveField(
            model_name='stoichiometryproblem',
            name='reactant_a_mass',
        ),
        migrations.AlterField(
            model_name='problempart',
            name='conversion_type',
            field=models.CharField(choices=[('mol_to_mol', 'mol A → mol B  (1 node)'), ('mol_to_g', 'mol A → g B    (2 nodes)'), ('g_to_mol', 'g A  → mol B   (2 nodes)'), ('g_to_g', 'g A  → g B     (3 nodes)')], default='g_to_g', max_length=20),
        ),
        migrations.AlterField(
            model_name='stoichiometryproblem',
            name='correct_coefficients',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='problempart',
            unique_together={('problem', 'part_label')},
        ),
    ]
