# Generated by Django 6.0.5 on 2026-05-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_problempart_limiting_given_quantities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problempart',
            name='limiting_given_quantities',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
