# Generated by Django 6.0.5 on 2026-05-29 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_alter_problempart_limiting_given_quantities'),
        ('core_app', '0006_userprofile'),
    ]

    operations = [
    ]
