# Generated by Django 6.0.5 on 2026-05-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_merge_20260529_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substance',
            name='id',
        ),
        migrations.AddField(
            model_name='substance',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='substance',
            name='group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='substance',
            name='is_element',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='substance',
            name='period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='display_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='substance',
            name='formula',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='substance',
            name='molar_mass',
            field=models.FloatField(),
        ),
    ]
